// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/zkproving/v1/service.proto

package zkprovingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZKProvingService_VerifyAge_FullMethodName          = "/zkproving.v1.ZKProvingService/VerifyAge"
	ZKProvingService_IssueCredential_FullMethodName    = "/zkproving.v1.ZKProvingService/IssueCredential"
	ZKProvingService_GetDateAttestation_FullMethodName = "/zkproving.v1.ZKProvingService/GetDateAttestation"
)

// ZKProvingServiceClient is the client API for ZKProvingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZKProvingServiceClient interface {
	VerifyAge(ctx context.Context, in *VerifyAgeRequest, opts ...grpc.CallOption) (*VerifyAgeResponse, error)
	IssueCredential(ctx context.Context, in *IssueCredentialRequest, opts ...grpc.CallOption) (*IssueCredentialResponse, error)
	GetDateAttestation(ctx context.Context, in *DateAttestationRequest, opts ...grpc.CallOption) (*DateAttestationResponse, error)
}

type zKProvingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZKProvingServiceClient(cc grpc.ClientConnInterface) ZKProvingServiceClient {
	return &zKProvingServiceClient{cc}
}

func (c *zKProvingServiceClient) VerifyAge(ctx context.Context, in *VerifyAgeRequest, opts ...grpc.CallOption) (*VerifyAgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAgeResponse)
	err := c.cc.Invoke(ctx, ZKProvingService_VerifyAge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKProvingServiceClient) IssueCredential(ctx context.Context, in *IssueCredentialRequest, opts ...grpc.CallOption) (*IssueCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCredentialResponse)
	err := c.cc.Invoke(ctx, ZKProvingService_IssueCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKProvingServiceClient) GetDateAttestation(ctx context.Context, in *DateAttestationRequest, opts ...grpc.CallOption) (*DateAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DateAttestationResponse)
	err := c.cc.Invoke(ctx, ZKProvingService_GetDateAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZKProvingServiceServer is the server API for ZKProvingService service.
// All implementations must embed UnimplementedZKProvingServiceServer
// for forward compatibility.
type ZKProvingServiceServer interface {
	VerifyAge(context.Context, *VerifyAgeRequest) (*VerifyAgeResponse, error)
	IssueCredential(context.Context, *IssueCredentialRequest) (*IssueCredentialResponse, error)
	GetDateAttestation(context.Context, *DateAttestationRequest) (*DateAttestationResponse, error)
	mustEmbedUnimplementedZKProvingServiceServer()
}

// UnimplementedZKProvingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZKProvingServiceServer struct{}

func (UnimplementedZKProvingServiceServer) VerifyAge(context.Context, *VerifyAgeRequest) (*VerifyAgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAge not implemented")
}
func (UnimplementedZKProvingServiceServer) IssueCredential(context.Context, *IssueCredentialRequest) (*IssueCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCredential not implemented")
}
func (UnimplementedZKProvingServiceServer) GetDateAttestation(context.Context, *DateAttestationRequest) (*DateAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDateAttestation not implemented")
}
func (UnimplementedZKProvingServiceServer) mustEmbedUnimplementedZKProvingServiceServer() {}
func (UnimplementedZKProvingServiceServer) testEmbeddedByValue()                          {}

// UnsafeZKProvingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZKProvingServiceServer will
// result in compilation errors.
type UnsafeZKProvingServiceServer interface {
	mustEmbedUnimplementedZKProvingServiceServer()
}

func RegisterZKProvingServiceServer(s grpc.ServiceRegistrar, srv ZKProvingServiceServer) {
	// If the following call panics, it indicates UnimplementedZKProvingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZKProvingService_ServiceDesc, srv)
}

func _ZKProvingService_VerifyAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKProvingServiceServer).VerifyAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZKProvingService_VerifyAge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKProvingServiceServer).VerifyAge(ctx, req.(*VerifyAgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKProvingService_IssueCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKProvingServiceServer).IssueCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZKProvingService_IssueCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKProvingServiceServer).IssueCredential(ctx, req.(*IssueCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKProvingService_GetDateAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKProvingServiceServer).GetDateAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZKProvingService_GetDateAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKProvingServiceServer).GetDateAttestation(ctx, req.(*DateAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZKProvingService_ServiceDesc is the grpc.ServiceDesc for ZKProvingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZKProvingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zkproving.v1.ZKProvingService",
	HandlerType: (*ZKProvingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyAge",
			Handler:    _ZKProvingService_VerifyAge_Handler,
		},
		{
			MethodName: "IssueCredential",
			Handler:    _ZKProvingService_IssueCredential_Handler,
		},
		{
			MethodName: "GetDateAttestation",
			Handler:    _ZKProvingService_GetDateAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/zkproving/v1/service.proto",
}
