// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: proto/zkproving/v1/service.proto

package zkprovingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyAgeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Proof           []byte                 `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	PublicInputs    []string               `protobuf:"bytes,2,rep,name=public_inputs,json=publicInputs,proto3" json:"public_inputs,omitempty"`
	Nullifier       string                 `protobuf:"bytes,3,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	StudyId         string                 `protobuf:"bytes,4,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	DateAttestation *DateAttestation       `protobuf:"bytes,5,opt,name=date_attestation,json=dateAttestation,proto3" json:"date_attestation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyAgeRequest) Reset() {
	*x = VerifyAgeRequest{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAgeRequest) ProtoMessage() {}

func (x *VerifyAgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAgeRequest.ProtoReflect.Descriptor instead.
func (*VerifyAgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyAgeRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *VerifyAgeRequest) GetPublicInputs() []string {
	if x != nil {
		return x.PublicInputs
	}
	return nil
}

func (x *VerifyAgeRequest) GetNullifier() string {
	if x != nil {
		return x.Nullifier
	}
	return ""
}

func (x *VerifyAgeRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *VerifyAgeRequest) GetDateAttestation() *DateAttestation {
	if x != nil {
		return x.DateAttestation
	}
	return nil
}

type VerifyAgeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZkSessionToken string                 `protobuf:"bytes,1,opt,name=zk_session_token,json=zkSessionToken,proto3" json:"zk_session_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyAgeResponse) Reset() {
	*x = VerifyAgeResponse{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAgeResponse) ProtoMessage() {}

func (x *VerifyAgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAgeResponse.ProtoReflect.Descriptor instead.
func (*VerifyAgeResponse) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyAgeResponse) GetZkSessionToken() string {
	if x != nil {
		return x.ZkSessionToken
	}
	return ""
}

type IssueCredentialRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgeProof        []byte                 `protobuf:"bytes,1,opt,name=age_proof,json=ageProof,proto3" json:"age_proof,omitempty"`
	AgePublicInputs []string               `protobuf:"bytes,2,rep,name=age_public_inputs,json=agePublicInputs,proto3" json:"age_public_inputs,omitempty"`
	Nullifier       string                 `protobuf:"bytes,3,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	StudyId         string                 `protobuf:"bytes,4,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	BlindingFactor  []byte                 `protobuf:"bytes,5,opt,name=blinding_factor,json=blindingFactor,proto3" json:"blinding_factor,omitempty"`
	Attributes      *StudyAttributes       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	DateAttestation *DateAttestation       `protobuf:"bytes,7,opt,name=date_attestation,json=dateAttestation,proto3" json:"date_attestation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueCredentialRequest) Reset() {
	*x = IssueCredentialRequest{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCredentialRequest) ProtoMessage() {}

func (x *IssueCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCredentialRequest.ProtoReflect.Descriptor instead.
func (*IssueCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *IssueCredentialRequest) GetAgeProof() []byte {
	if x != nil {
		return x.AgeProof
	}
	return nil
}

func (x *IssueCredentialRequest) GetAgePublicInputs() []string {
	if x != nil {
		return x.AgePublicInputs
	}
	return nil
}

func (x *IssueCredentialRequest) GetNullifier() string {
	if x != nil {
		return x.Nullifier
	}
	return ""
}

func (x *IssueCredentialRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

func (x *IssueCredentialRequest) GetBlindingFactor() []byte {
	if x != nil {
		return x.BlindingFactor
	}
	return nil
}

func (x *IssueCredentialRequest) GetAttributes() *StudyAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *IssueCredentialRequest) GetDateAttestation() *DateAttestation {
	if x != nil {
		return x.DateAttestation
	}
	return nil
}

type IssueCredentialResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ZkSessionToken       string                 `protobuf:"bytes,1,opt,name=zk_session_token,json=zkSessionToken,proto3" json:"zk_session_token,omitempty"`
	CredentialCommitment string                 `protobuf:"bytes,2,opt,name=credential_commitment,json=credentialCommitment,proto3" json:"credential_commitment,omitempty"`
	ReceiptSeal          string                 `protobuf:"bytes,3,opt,name=receipt_seal,json=receiptSeal,proto3" json:"receipt_seal,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IssueCredentialResponse) Reset() {
	*x = IssueCredentialResponse{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCredentialResponse) ProtoMessage() {}

func (x *IssueCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCredentialResponse.ProtoReflect.Descriptor instead.
func (*IssueCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *IssueCredentialResponse) GetZkSessionToken() string {
	if x != nil {
		return x.ZkSessionToken
	}
	return ""
}

func (x *IssueCredentialResponse) GetCredentialCommitment() string {
	if x != nil {
		return x.CredentialCommitment
	}
	return ""
}

func (x *IssueCredentialResponse) GetReceiptSeal() string {
	if x != nil {
		return x.ReceiptSeal
	}
	return ""
}

type DateAttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyId       string                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateAttestationRequest) Reset() {
	*x = DateAttestationRequest{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateAttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateAttestationRequest) ProtoMessage() {}

func (x *DateAttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateAttestationRequest.ProtoReflect.Descriptor instead.
func (*DateAttestationRequest) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DateAttestationRequest) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

type DateAttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestation   *DateAttestation       `protobuf:"bytes,1,opt,name=attestation,proto3" json:"attestation,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateAttestationResponse) Reset() {
	*x = DateAttestationResponse{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateAttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateAttestationResponse) ProtoMessage() {}

func (x *DateAttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateAttestationResponse.ProtoReflect.Descriptor instead.
func (*DateAttestationResponse) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *DateAttestationResponse) GetAttestation() *DateAttestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *DateAttestationResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type DateAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          uint32                 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         uint32                 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           uint32                 `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	SignedAt      int64                  `protobuf:"varint,4,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	StudyId       string                 `protobuf:"bytes,6,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateAttestation) Reset() {
	*x = DateAttestation{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateAttestation) ProtoMessage() {}

func (x *DateAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateAttestation.ProtoReflect.Descriptor instead.
func (*DateAttestation) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *DateAttestation) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *DateAttestation) GetMonth() uint32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *DateAttestation) GetDay() uint32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *DateAttestation) GetSignedAt() int64 {
	if x != nil {
		return x.SignedAt
	}
	return 0
}

func (x *DateAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DateAttestation) GetStudyId() string {
	if x != nil {
		return x.StudyId
	}
	return ""
}

type StudyAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgeRange      string                 `protobuf:"bytes,1,opt,name=age_range,json=ageRange,proto3" json:"age_range,omitempty"`
	CountryBucket string                 `protobuf:"bytes,2,opt,name=country_bucket,json=countryBucket,proto3" json:"country_bucket,omitempty"`
	Interests     []string               `protobuf:"bytes,3,rep,name=interests,proto3" json:"interests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyAttributes) Reset() {
	*x = StudyAttributes{}
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyAttributes) ProtoMessage() {}

func (x *StudyAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkproving_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyAttributes.ProtoReflect.Descriptor instead.
func (*StudyAttributes) Descriptor() ([]byte, []int) {
	return file_proto_zkproving_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *StudyAttributes) GetAgeRange() string {
	if x != nil {
		return x.AgeRange
	}
	return ""
}

func (x *StudyAttributes) GetCountryBucket() string {
	if x != nil {
		return x.CountryBucket
	}
	return ""
}

func (x *StudyAttributes) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

var File_proto_zkproving_v1_service_proto protoreflect.FileDescriptor

const file_proto_zkproving_v1_service_proto_rawDesc = "" +
	"\n" +
	" proto/zkproving/v1/service.proto\x12\fzkproving.v1\"\xd0\x01\n" +
	"\x10VerifyAgeRequest\x12\x14\n" +
	"\x05proof\x18\x01 \x01(\fR\x05proof\x12#\n" +
	"\rpublic_inputs\x18\x02 \x03(\tR\fpublicInputs\x12\x1c\n" +
	"\tnullifier\x18\x03 \x01(\tR\tnullifier\x12\x19\n" +
	"\bstudy_id\x18\x04 \x01(\tR\astudyId\x12H\n" +
	"\x10date_attestation\x18\x05 \x01(\v2\x1d.zkproving.v1.DateAttestationR\x0fdateAttestation\"=\n" +
	"\x11VerifyAgeResponse\x12(\n" +
	"\x10zk_session_token\x18\x01 \x01(\tR\x0ezkSessionToken\"\xcc\x02\n" +
	"\x16IssueCredentialRequest\x12\x1b\n" +
	"\tage_proof\x18\x01 \x01(\fR\bageProof\x12*\n" +
	"\x11age_public_inputs\x18\x02 \x03(\tR\x0fagePublicInputs\x12\x1c\n" +
	"\tnullifier\x18\x03 \x01(\tR\tnullifier\x12\x19\n" +
	"\bstudy_id\x18\x04 \x01(\tR\astudyId\x12'\n" +
	"\x0fblinding_factor\x18\x05 \x01(\fR\x0eblindingFactor\x12=\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x1d.zkproving.v1.StudyAttributesR\n" +
	"attributes\x12H\n" +
	"\x10date_attestation\x18\a \x01(\v2\x1d.zkproving.v1.DateAttestationR\x0fdateAttestation\"\x9b\x01\n" +
	"\x17IssueCredentialResponse\x12(\n" +
	"\x10zk_session_token\x18\x01 \x01(\tR\x0ezkSessionToken\x123\n" +
	"\x15credential_commitment\x18\x02 \x01(\tR\x14credentialCommitment\x12!\n" +
	"\freceipt_seal\x18\x03 \x01(\tR\vreceiptSeal\"3\n" +
	"\x16DateAttestationRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\tR\astudyId\"y\n" +
	"\x17DateAttestationResponse\x12?\n" +
	"\vattestation\x18\x01 \x01(\v2\x1d.zkproving.v1.DateAttestationR\vattestation\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xa3\x01\n" +
	"\x0fDateAttestation\x12\x12\n" +
	"\x04year\x18\x01 \x01(\rR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\rR\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\rR\x03day\x12\x1b\n" +
	"\tsigned_at\x18\x04 \x01(\x03R\bsignedAt\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x19\n" +
	"\bstudy_id\x18\x06 \x01(\tR\astudyId\"s\n" +
	"\x0fStudyAttributes\x12\x1b\n" +
	"\tage_range\x18\x01 \x01(\tR\bageRange\x12%\n" +
	"\x0ecountry_bucket\x18\x02 \x01(\tR\rcountryBucket\x12\x1c\n" +
	"\tinterests\x18\x03 \x03(\tR\tinterests2\xa3\x02\n" +
	"\x10ZKProvingService\x12L\n" +
	"\tVerifyAge\x12\x1e.zkproving.v1.VerifyAgeRequest\x1a\x1f.zkproving.v1.VerifyAgeResponse\x12^\n" +
	"\x0fIssueCredential\x12$.zkproving.v1.IssueCredentialRequest\x1a%.zkproving.v1.IssueCredentialResponse\x12a\n" +
	"\x12GetDateAttestation\x12$.zkproving.v1.DateAttestationRequest\x1a%.zkproving.v1.DateAttestationResponseBJZHgithub.com/quantumworld/panel/api-gateway/proto/zkproving/v1;zkprovingv1b\x06proto3"

var (
	file_proto_zkproving_v1_service_proto_rawDescOnce sync.Once
	file_proto_zkproving_v1_service_proto_rawDescData []byte
)

func file_proto_zkproving_v1_service_proto_rawDescGZIP() []byte {
	file_proto_zkproving_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_zkproving_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zkproving_v1_service_proto_rawDesc), len(file_proto_zkproving_v1_service_proto_rawDesc)))
	})
	return file_proto_zkproving_v1_service_proto_rawDescData
}

var file_proto_zkproving_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_zkproving_v1_service_proto_goTypes = []any{
	(*VerifyAgeRequest)(nil),        // 0: zkproving.v1.VerifyAgeRequest
	(*VerifyAgeResponse)(nil),       // 1: zkproving.v1.VerifyAgeResponse
	(*IssueCredentialRequest)(nil),  // 2: zkproving.v1.IssueCredentialRequest
	(*IssueCredentialResponse)(nil), // 3: zkproving.v1.IssueCredentialResponse
	(*DateAttestationRequest)(nil),  // 4: zkproving.v1.DateAttestationRequest
	(*DateAttestationResponse)(nil), // 5: zkproving.v1.DateAttestationResponse
	(*DateAttestation)(nil),         // 6: zkproving.v1.DateAttestation
	(*StudyAttributes)(nil),         // 7: zkproving.v1.StudyAttributes
}
var file_proto_zkproving_v1_service_proto_depIdxs = []int32{
	6, // 0: zkproving.v1.VerifyAgeRequest.date_attestation:type_name -> zkproving.v1.DateAttestation
	7, // 1: zkproving.v1.IssueCredentialRequest.attributes:type_name -> zkproving.v1.StudyAttributes
	6, // 2: zkproving.v1.IssueCredentialRequest.date_attestation:type_name -> zkproving.v1.DateAttestation
	6, // 3: zkproving.v1.DateAttestationResponse.attestation:type_name -> zkproving.v1.DateAttestation
	0, // 4: zkproving.v1.ZKProvingService.VerifyAge:input_type -> zkproving.v1.VerifyAgeRequest
	2, // 5: zkproving.v1.ZKProvingService.IssueCredential:input_type -> zkproving.v1.IssueCredentialRequest
	4, // 6: zkproving.v1.ZKProvingService.GetDateAttestation:input_type -> zkproving.v1.DateAttestationRequest
	1, // 7: zkproving.v1.ZKProvingService.VerifyAge:output_type -> zkproving.v1.VerifyAgeResponse
	3, // 8: zkproving.v1.ZKProvingService.IssueCredential:output_type -> zkproving.v1.IssueCredentialResponse
	5, // 9: zkproving.v1.ZKProvingService.GetDateAttestation:output_type -> zkproving.v1.DateAttestationResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_zkproving_v1_service_proto_init() }
func file_proto_zkproving_v1_service_proto_init() {
	if File_proto_zkproving_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zkproving_v1_service_proto_rawDesc), len(file_proto_zkproving_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zkproving_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_zkproving_v1_service_proto_depIdxs,
		MessageInfos:      file_proto_zkproving_v1_service_proto_msgTypes,
	}.Build()
	File_proto_zkproving_v1_service_proto = out.File
	file_proto_zkproving_v1_service_proto_goTypes = nil
	file_proto_zkproving_v1_service_proto_depIdxs = nil
}
