mod config;
mod error;
mod grpc;
mod handlers;
mod nullifier;
mod state;
mod token;
mod zk;

use axum::{routing::{get, post}, Router};
use std::net::SocketAddr;
use tower_http::{timeout::TimeoutLayer, trace::TraceLayer};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};
use state::AppState;

// Pull in tonic-generated server trait + wrapper (generated by build.rs via tonic_build)
use grpc::service::{
    zk_proving_service_server::ZkProvingServiceServer,
    ZKProvingGrpcService,
};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::registry()
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()))
        .with(tracing_subscriber::fmt::layer().json())
        .init();

    let cfg = config::Config::from_env()?;
    tracing::info!(http = %cfg.listen_addr, grpc = %cfg.grpc_addr, "ZK Proving Service starting");

    let state = AppState::new(cfg.clone()).await?;

    // ── Axum HTTP server ──────────────────────────────────────────────────────
    let http_router = build_http_router(state.clone());
    let http_addr: SocketAddr = cfg.listen_addr.parse()?;
    let http_listener = tokio::net::TcpListener::bind(http_addr).await?;
    let http_server = async move {
        tracing::info!("HTTP listening on {}", http_addr);
        axum::serve(http_listener, http_router)
            .await
            .map_err(|e| anyhow::anyhow!("HTTP server error: {}", e))
    };

    // ── Tonic gRPC server ─────────────────────────────────────────────────────
    let grpc_addr: SocketAddr = cfg.grpc_addr.parse()?;
    let grpc_service = ZKProvingGrpcService { state };
    let grpc_server = async move {
        tracing::info!("gRPC listening on {}", grpc_addr);
        tonic::transport::Server::builder()
            .add_service(ZkProvingServiceServer::new(grpc_service))
            .serve(grpc_addr)
            .await
            .map_err(|e| anyhow::anyhow!("gRPC server error: {}", e))
    };

    // ── Run both concurrently; either failure shuts down the process ──────────
    tokio::try_join!(http_server, grpc_server)?;

    Ok(())
}

fn build_http_router(state: AppState) -> Router {
    Router::new()
        .route("/zk/verify-age",       post(handlers::verify_age::handler))
        .route("/zk/issue-credential", post(handlers::issue_credential::handler))
        .route("/zk/date-attestation", get(handlers::date_attestation::handler))
        .route("/health",              get(health))
        .with_state(state)
        .layer(TraceLayer::new_for_http())
        .layer(TimeoutLayer::new(std::time::Duration::from_secs(30)))
}

async fn health() -> &'static str { "ok" }
