use risc0_zkvm::{default_prover, ExecutorEnv, Receipt};
use serde::{Deserialize, Serialize};
use crate::config::Config;
use crate::error::AppError;

// Generated by build.rs from the guest crate.
// Contains CREDENTIAL_GUEST_ELF (bytes) and CREDENTIAL_GUEST_ID ([u32; 8]).
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StudyAttrs {
    pub age_range: String,
    pub country_bucket: String,
    pub interests: Vec<String>,
}

impl StudyAttrs {
    /// Check that participant's self-reported attributes match study targeting.
    pub fn matches_criteria(&self) -> bool {
        // Criteria matching is done against study config fetched from Supabase.
        // At this layer we accept any non-empty attribute set (criteria enforced by host).
        !self.age_range.is_empty() && !self.country_bucket.is_empty()
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CredentialRequest {
    pub nullifier: String,
    pub study_id: String,
    /// Set to true only after host has verified the Barretenberg age proof.
    pub age_proof_valid: bool,
    pub study_attributes: StudyAttrs,
    pub blinding_factor: [u8; 32],
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CredentialJournal {
    pub credential_commitment: [u8; 32],
    pub nullifier_hash: [u8; 32],
    pub study_id: String,
    pub issued_at: i64,
    pub attributes_hash: [u8; 32],
}

pub struct CredentialIssuer;

impl CredentialIssuer {
    pub fn new(_config: &Config) -> anyhow::Result<Self> {
        Ok(Self)
    }

    /// Run the credential issuance guest inside the RISC Zero zkVM.
    /// Returns (journal, receipt) on success.
    pub async fn issue(
        &self,
        request: CredentialRequest,
    ) -> Result<(CredentialJournal, Receipt), AppError> {
        tokio::task::spawn_blocking(move || {
            let env = ExecutorEnv::builder()
                .write(&request)
                .map_err(|e| anyhow::anyhow!("env write: {}", e))?
                .build()
                .map_err(|e| anyhow::anyhow!("env build: {}", e))?;

            let prover = default_prover();

            let receipt = prover
                .prove(env, CREDENTIAL_GUEST_ELF)
                .map_err(|e| anyhow::anyhow!("prove: {}", e))?;

            // Verify the receipt against the pinned Image ID.
            // This catches RISC0_DEV_MODE=1 fake receipts in production.
            receipt
                .verify(CREDENTIAL_GUEST_ID)
                .map_err(|e| anyhow::anyhow!("verify: {}", e))?;

            let journal: CredentialJournal = receipt
                .journal
                .decode()
                .map_err(|e| anyhow::anyhow!("decode: {}", e))?;

            Ok::<_, anyhow::Error>((journal, receipt))
        })
        .await
        .map_err(|e| AppError::Internal(anyhow::anyhow!("spawn_blocking: {}", e)))?
        .map_err(|e| AppError::Internal(e))
    }
}
